# Dockerfile.nginx
FROM nginx:alpine

# Copiar el directorio public desde la imagen de PHP-FPM (que incluye los assets de Vite)
#COPY --from=laravel_app /var/www/html/public /var/www/html/public

# Copiar la configuración de Nginx
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Ajustar permisos para Nginx
# Crear el directorio donde nginx esperará los archivos
RUN mkdir -p /var/www/html/public && \
    chown -R nginx:nginx /var/www/html && \
    chmod -R 755 /var/www/html
